name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    name: "Lint & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "17"
          cache: "npm"
      - run: npm run setup
      - run: npm run lint
      - run: npm run type-check
      - run: npm run test
